package com.best.oasis.bexom.common.entity.v3;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SalaryEmpMonthly implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.ID
     *
     * @mbg.generated
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.EMP_ID
     *
     * @mbg.generated
     */
    private BigDecimal empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.SITE_ID
     *
     * @mbg.generated
     */
    private BigDecimal siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.DELIVERY_QUANTITY
     *
     * @mbg.generated
     */
    private Long deliveryQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.DELIVERY_POINT
     *
     * @mbg.generated
     */
    private BigDecimal deliveryPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.RETURN_POINT
     *
     * @mbg.generated
     */
    private BigDecimal returnPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.RETURN_QUANTITY
     *
     * @mbg.generated
     */
    private Long returnQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.PICKUP_POINT
     *
     * @mbg.generated
     */
    private BigDecimal pickupPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.PICKUP_QUANTITY
     *
     * @mbg.generated
     */
    private Long pickupQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.ACTUAL_WORK_DAY
     *
     * @mbg.generated
     */
    private Long actualWorkDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.STANDARD_WORK_DAY
     *
     * @mbg.generated
     */
    private Long standardWorkDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.YEAR_MONTH
     *
     * @mbg.generated
     */
    private Object yearMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.BASIC_SALARY
     *
     * @mbg.generated
     */
    private BigDecimal basicSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.DELIVERY_SALARY
     *
     * @mbg.generated
     */
    private BigDecimal deliverySalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.RETURN_SALARY
     *
     * @mbg.generated
     */
    private BigDecimal returnSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.PICKUP_SALARY
     *
     * @mbg.generated
     */
    private BigDecimal pickupSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.POINT_SALARY
     *
     * @mbg.generated
     */
    private BigDecimal pointSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.ATTENDANCE_SALARY
     *
     * @mbg.generated
     */
    private BigDecimal attendanceSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.ACTUAL_SALARY
     *
     * @mbg.generated
     */
    private BigDecimal actualSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.CREATOR
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.CREATOR_NAME
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.LAST_UPDATOR
     *
     * @mbg.generated
     */
    private String lastUpdator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.LAST_UPDATOR_NAME
     *
     * @mbg.generated
     */
    private String lastUpdatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_EMP_MONTHLY.LOCK_VERSION
     *
     * @mbg.generated
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SALARY_EMP_MONTHLY
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.ID
     *
     * @return the value of SALARY_EMP_MONTHLY.ID
     *
     * @mbg.generated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.ID
     *
     * @param id the value for SALARY_EMP_MONTHLY.ID
     *
     * @mbg.generated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.EMP_ID
     *
     * @return the value of SALARY_EMP_MONTHLY.EMP_ID
     *
     * @mbg.generated
     */
    public BigDecimal getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.EMP_ID
     *
     * @param empId the value for SALARY_EMP_MONTHLY.EMP_ID
     *
     * @mbg.generated
     */
    public void setEmpId(BigDecimal empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.SITE_ID
     *
     * @return the value of SALARY_EMP_MONTHLY.SITE_ID
     *
     * @mbg.generated
     */
    public BigDecimal getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.SITE_ID
     *
     * @param siteId the value for SALARY_EMP_MONTHLY.SITE_ID
     *
     * @mbg.generated
     */
    public void setSiteId(BigDecimal siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.DELIVERY_QUANTITY
     *
     * @return the value of SALARY_EMP_MONTHLY.DELIVERY_QUANTITY
     *
     * @mbg.generated
     */
    public Long getDeliveryQuantity() {
        return deliveryQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.DELIVERY_QUANTITY
     *
     * @param deliveryQuantity the value for SALARY_EMP_MONTHLY.DELIVERY_QUANTITY
     *
     * @mbg.generated
     */
    public void setDeliveryQuantity(Long deliveryQuantity) {
        this.deliveryQuantity = deliveryQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.DELIVERY_POINT
     *
     * @return the value of SALARY_EMP_MONTHLY.DELIVERY_POINT
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryPoint() {
        return deliveryPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.DELIVERY_POINT
     *
     * @param deliveryPoint the value for SALARY_EMP_MONTHLY.DELIVERY_POINT
     *
     * @mbg.generated
     */
    public void setDeliveryPoint(BigDecimal deliveryPoint) {
        this.deliveryPoint = deliveryPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.RETURN_POINT
     *
     * @return the value of SALARY_EMP_MONTHLY.RETURN_POINT
     *
     * @mbg.generated
     */
    public BigDecimal getReturnPoint() {
        return returnPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.RETURN_POINT
     *
     * @param returnPoint the value for SALARY_EMP_MONTHLY.RETURN_POINT
     *
     * @mbg.generated
     */
    public void setReturnPoint(BigDecimal returnPoint) {
        this.returnPoint = returnPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.RETURN_QUANTITY
     *
     * @return the value of SALARY_EMP_MONTHLY.RETURN_QUANTITY
     *
     * @mbg.generated
     */
    public Long getReturnQuantity() {
        return returnQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.RETURN_QUANTITY
     *
     * @param returnQuantity the value for SALARY_EMP_MONTHLY.RETURN_QUANTITY
     *
     * @mbg.generated
     */
    public void setReturnQuantity(Long returnQuantity) {
        this.returnQuantity = returnQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.PICKUP_POINT
     *
     * @return the value of SALARY_EMP_MONTHLY.PICKUP_POINT
     *
     * @mbg.generated
     */
    public BigDecimal getPickupPoint() {
        return pickupPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.PICKUP_POINT
     *
     * @param pickupPoint the value for SALARY_EMP_MONTHLY.PICKUP_POINT
     *
     * @mbg.generated
     */
    public void setPickupPoint(BigDecimal pickupPoint) {
        this.pickupPoint = pickupPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.PICKUP_QUANTITY
     *
     * @return the value of SALARY_EMP_MONTHLY.PICKUP_QUANTITY
     *
     * @mbg.generated
     */
    public Long getPickupQuantity() {
        return pickupQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.PICKUP_QUANTITY
     *
     * @param pickupQuantity the value for SALARY_EMP_MONTHLY.PICKUP_QUANTITY
     *
     * @mbg.generated
     */
    public void setPickupQuantity(Long pickupQuantity) {
        this.pickupQuantity = pickupQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.ACTUAL_WORK_DAY
     *
     * @return the value of SALARY_EMP_MONTHLY.ACTUAL_WORK_DAY
     *
     * @mbg.generated
     */
    public Long getActualWorkDay() {
        return actualWorkDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.ACTUAL_WORK_DAY
     *
     * @param actualWorkDay the value for SALARY_EMP_MONTHLY.ACTUAL_WORK_DAY
     *
     * @mbg.generated
     */
    public void setActualWorkDay(Long actualWorkDay) {
        this.actualWorkDay = actualWorkDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.STANDARD_WORK_DAY
     *
     * @return the value of SALARY_EMP_MONTHLY.STANDARD_WORK_DAY
     *
     * @mbg.generated
     */
    public Long getStandardWorkDay() {
        return standardWorkDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.STANDARD_WORK_DAY
     *
     * @param standardWorkDay the value for SALARY_EMP_MONTHLY.STANDARD_WORK_DAY
     *
     * @mbg.generated
     */
    public void setStandardWorkDay(Long standardWorkDay) {
        this.standardWorkDay = standardWorkDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.YEAR_MONTH
     *
     * @return the value of SALARY_EMP_MONTHLY.YEAR_MONTH
     *
     * @mbg.generated
     */
    public Object getYearMonth() {
        return yearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.YEAR_MONTH
     *
     * @param yearMonth the value for SALARY_EMP_MONTHLY.YEAR_MONTH
     *
     * @mbg.generated
     */
    public void setYearMonth(Object yearMonth) {
        this.yearMonth = yearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.BASIC_SALARY
     *
     * @return the value of SALARY_EMP_MONTHLY.BASIC_SALARY
     *
     * @mbg.generated
     */
    public BigDecimal getBasicSalary() {
        return basicSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.BASIC_SALARY
     *
     * @param basicSalary the value for SALARY_EMP_MONTHLY.BASIC_SALARY
     *
     * @mbg.generated
     */
    public void setBasicSalary(BigDecimal basicSalary) {
        this.basicSalary = basicSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.DELIVERY_SALARY
     *
     * @return the value of SALARY_EMP_MONTHLY.DELIVERY_SALARY
     *
     * @mbg.generated
     */
    public BigDecimal getDeliverySalary() {
        return deliverySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.DELIVERY_SALARY
     *
     * @param deliverySalary the value for SALARY_EMP_MONTHLY.DELIVERY_SALARY
     *
     * @mbg.generated
     */
    public void setDeliverySalary(BigDecimal deliverySalary) {
        this.deliverySalary = deliverySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.RETURN_SALARY
     *
     * @return the value of SALARY_EMP_MONTHLY.RETURN_SALARY
     *
     * @mbg.generated
     */
    public BigDecimal getReturnSalary() {
        return returnSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.RETURN_SALARY
     *
     * @param returnSalary the value for SALARY_EMP_MONTHLY.RETURN_SALARY
     *
     * @mbg.generated
     */
    public void setReturnSalary(BigDecimal returnSalary) {
        this.returnSalary = returnSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.PICKUP_SALARY
     *
     * @return the value of SALARY_EMP_MONTHLY.PICKUP_SALARY
     *
     * @mbg.generated
     */
    public BigDecimal getPickupSalary() {
        return pickupSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.PICKUP_SALARY
     *
     * @param pickupSalary the value for SALARY_EMP_MONTHLY.PICKUP_SALARY
     *
     * @mbg.generated
     */
    public void setPickupSalary(BigDecimal pickupSalary) {
        this.pickupSalary = pickupSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.POINT_SALARY
     *
     * @return the value of SALARY_EMP_MONTHLY.POINT_SALARY
     *
     * @mbg.generated
     */
    public BigDecimal getPointSalary() {
        return pointSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.POINT_SALARY
     *
     * @param pointSalary the value for SALARY_EMP_MONTHLY.POINT_SALARY
     *
     * @mbg.generated
     */
    public void setPointSalary(BigDecimal pointSalary) {
        this.pointSalary = pointSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.ATTENDANCE_SALARY
     *
     * @return the value of SALARY_EMP_MONTHLY.ATTENDANCE_SALARY
     *
     * @mbg.generated
     */
    public BigDecimal getAttendanceSalary() {
        return attendanceSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.ATTENDANCE_SALARY
     *
     * @param attendanceSalary the value for SALARY_EMP_MONTHLY.ATTENDANCE_SALARY
     *
     * @mbg.generated
     */
    public void setAttendanceSalary(BigDecimal attendanceSalary) {
        this.attendanceSalary = attendanceSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.ACTUAL_SALARY
     *
     * @return the value of SALARY_EMP_MONTHLY.ACTUAL_SALARY
     *
     * @mbg.generated
     */
    public BigDecimal getActualSalary() {
        return actualSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.ACTUAL_SALARY
     *
     * @param actualSalary the value for SALARY_EMP_MONTHLY.ACTUAL_SALARY
     *
     * @mbg.generated
     */
    public void setActualSalary(BigDecimal actualSalary) {
        this.actualSalary = actualSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.CREATE_TIME
     *
     * @return the value of SALARY_EMP_MONTHLY.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.CREATE_TIME
     *
     * @param createTime the value for SALARY_EMP_MONTHLY.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.CREATOR
     *
     * @return the value of SALARY_EMP_MONTHLY.CREATOR
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.CREATOR
     *
     * @param creator the value for SALARY_EMP_MONTHLY.CREATOR
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.CREATOR_NAME
     *
     * @return the value of SALARY_EMP_MONTHLY.CREATOR_NAME
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.CREATOR_NAME
     *
     * @param creatorName the value for SALARY_EMP_MONTHLY.CREATOR_NAME
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.LAST_UPDATE_TIME
     *
     * @return the value of SALARY_EMP_MONTHLY.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for SALARY_EMP_MONTHLY.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.LAST_UPDATOR
     *
     * @return the value of SALARY_EMP_MONTHLY.LAST_UPDATOR
     *
     * @mbg.generated
     */
    public String getLastUpdator() {
        return lastUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.LAST_UPDATOR
     *
     * @param lastUpdator the value for SALARY_EMP_MONTHLY.LAST_UPDATOR
     *
     * @mbg.generated
     */
    public void setLastUpdator(String lastUpdator) {
        this.lastUpdator = lastUpdator == null ? null : lastUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.LAST_UPDATOR_NAME
     *
     * @return the value of SALARY_EMP_MONTHLY.LAST_UPDATOR_NAME
     *
     * @mbg.generated
     */
    public String getLastUpdatorName() {
        return lastUpdatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.LAST_UPDATOR_NAME
     *
     * @param lastUpdatorName the value for SALARY_EMP_MONTHLY.LAST_UPDATOR_NAME
     *
     * @mbg.generated
     */
    public void setLastUpdatorName(String lastUpdatorName) {
        this.lastUpdatorName = lastUpdatorName == null ? null : lastUpdatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.REMARK
     *
     * @return the value of SALARY_EMP_MONTHLY.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.REMARK
     *
     * @param remark the value for SALARY_EMP_MONTHLY.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_EMP_MONTHLY.LOCK_VERSION
     *
     * @return the value of SALARY_EMP_MONTHLY.LOCK_VERSION
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_EMP_MONTHLY.LOCK_VERSION
     *
     * @param version the value for SALARY_EMP_MONTHLY.LOCK_VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALARY_EMP_MONTHLY
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SalaryEmpMonthly other = (SalaryEmpMonthly) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEmpId() == null ? other.getEmpId() == null : this.getEmpId().equals(other.getEmpId()))
            && (this.getSiteId() == null ? other.getSiteId() == null : this.getSiteId().equals(other.getSiteId()))
            && (this.getDeliveryQuantity() == null ? other.getDeliveryQuantity() == null : this.getDeliveryQuantity().equals(other.getDeliveryQuantity()))
            && (this.getDeliveryPoint() == null ? other.getDeliveryPoint() == null : this.getDeliveryPoint().equals(other.getDeliveryPoint()))
            && (this.getReturnPoint() == null ? other.getReturnPoint() == null : this.getReturnPoint().equals(other.getReturnPoint()))
            && (this.getReturnQuantity() == null ? other.getReturnQuantity() == null : this.getReturnQuantity().equals(other.getReturnQuantity()))
            && (this.getPickupPoint() == null ? other.getPickupPoint() == null : this.getPickupPoint().equals(other.getPickupPoint()))
            && (this.getPickupQuantity() == null ? other.getPickupQuantity() == null : this.getPickupQuantity().equals(other.getPickupQuantity()))
            && (this.getActualWorkDay() == null ? other.getActualWorkDay() == null : this.getActualWorkDay().equals(other.getActualWorkDay()))
            && (this.getStandardWorkDay() == null ? other.getStandardWorkDay() == null : this.getStandardWorkDay().equals(other.getStandardWorkDay()))
            && (this.getYearMonth() == null ? other.getYearMonth() == null : this.getYearMonth().equals(other.getYearMonth()))
            && (this.getBasicSalary() == null ? other.getBasicSalary() == null : this.getBasicSalary().equals(other.getBasicSalary()))
            && (this.getDeliverySalary() == null ? other.getDeliverySalary() == null : this.getDeliverySalary().equals(other.getDeliverySalary()))
            && (this.getReturnSalary() == null ? other.getReturnSalary() == null : this.getReturnSalary().equals(other.getReturnSalary()))
            && (this.getPickupSalary() == null ? other.getPickupSalary() == null : this.getPickupSalary().equals(other.getPickupSalary()))
            && (this.getPointSalary() == null ? other.getPointSalary() == null : this.getPointSalary().equals(other.getPointSalary()))
            && (this.getAttendanceSalary() == null ? other.getAttendanceSalary() == null : this.getAttendanceSalary().equals(other.getAttendanceSalary()))
            && (this.getActualSalary() == null ? other.getActualSalary() == null : this.getActualSalary().equals(other.getActualSalary()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreatorName() == null ? other.getCreatorName() == null : this.getCreatorName().equals(other.getCreatorName()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdator() == null ? other.getLastUpdator() == null : this.getLastUpdator().equals(other.getLastUpdator()))
            && (this.getLastUpdatorName() == null ? other.getLastUpdatorName() == null : this.getLastUpdatorName().equals(other.getLastUpdatorName()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALARY_EMP_MONTHLY
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEmpId() == null) ? 0 : getEmpId().hashCode());
        result = prime * result + ((getSiteId() == null) ? 0 : getSiteId().hashCode());
        result = prime * result + ((getDeliveryQuantity() == null) ? 0 : getDeliveryQuantity().hashCode());
        result = prime * result + ((getDeliveryPoint() == null) ? 0 : getDeliveryPoint().hashCode());
        result = prime * result + ((getReturnPoint() == null) ? 0 : getReturnPoint().hashCode());
        result = prime * result + ((getReturnQuantity() == null) ? 0 : getReturnQuantity().hashCode());
        result = prime * result + ((getPickupPoint() == null) ? 0 : getPickupPoint().hashCode());
        result = prime * result + ((getPickupQuantity() == null) ? 0 : getPickupQuantity().hashCode());
        result = prime * result + ((getActualWorkDay() == null) ? 0 : getActualWorkDay().hashCode());
        result = prime * result + ((getStandardWorkDay() == null) ? 0 : getStandardWorkDay().hashCode());
        result = prime * result + ((getYearMonth() == null) ? 0 : getYearMonth().hashCode());
        result = prime * result + ((getBasicSalary() == null) ? 0 : getBasicSalary().hashCode());
        result = prime * result + ((getDeliverySalary() == null) ? 0 : getDeliverySalary().hashCode());
        result = prime * result + ((getReturnSalary() == null) ? 0 : getReturnSalary().hashCode());
        result = prime * result + ((getPickupSalary() == null) ? 0 : getPickupSalary().hashCode());
        result = prime * result + ((getPointSalary() == null) ? 0 : getPointSalary().hashCode());
        result = prime * result + ((getAttendanceSalary() == null) ? 0 : getAttendanceSalary().hashCode());
        result = prime * result + ((getActualSalary() == null) ? 0 : getActualSalary().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreatorName() == null) ? 0 : getCreatorName().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdator() == null) ? 0 : getLastUpdator().hashCode());
        result = prime * result + ((getLastUpdatorName() == null) ? 0 : getLastUpdatorName().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALARY_EMP_MONTHLY
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", empId=").append(empId);
        sb.append(", siteId=").append(siteId);
        sb.append(", deliveryQuantity=").append(deliveryQuantity);
        sb.append(", deliveryPoint=").append(deliveryPoint);
        sb.append(", returnPoint=").append(returnPoint);
        sb.append(", returnQuantity=").append(returnQuantity);
        sb.append(", pickupPoint=").append(pickupPoint);
        sb.append(", pickupQuantity=").append(pickupQuantity);
        sb.append(", actualWorkDay=").append(actualWorkDay);
        sb.append(", standardWorkDay=").append(standardWorkDay);
        sb.append(", yearMonth=").append(yearMonth);
        sb.append(", basicSalary=").append(basicSalary);
        sb.append(", deliverySalary=").append(deliverySalary);
        sb.append(", returnSalary=").append(returnSalary);
        sb.append(", pickupSalary=").append(pickupSalary);
        sb.append(", pointSalary=").append(pointSalary);
        sb.append(", attendanceSalary=").append(attendanceSalary);
        sb.append(", actualSalary=").append(actualSalary);
        sb.append(", createTime=").append(createTime);
        sb.append(", creator=").append(creator);
        sb.append(", creatorName=").append(creatorName);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", lastUpdator=").append(lastUpdator);
        sb.append(", lastUpdatorName=").append(lastUpdatorName);
        sb.append(", remark=").append(remark);
        sb.append(", version=").append(version);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}